import { MD3LightTheme, MD3DarkTheme, configureFonts } from 'react-native-paper';
import { colors } from './colors';

const fontConfig = {
  displayLarge: { fontFamily: 'System', fontSize: 57, fontWeight: '400' as const, letterSpacing: 0 },
  displayMedium: { fontFamily: 'System', fontSize: 45, fontWeight: '400' as const, letterSpacing: 0 },
  displaySmall: { fontFamily: 'System', fontSize: 36, fontWeight: '400' as const, letterSpacing: 0 },
  headlineLarge: { fontFamily: 'System', fontSize: 32, fontWeight: '400' as const, letterSpacing: 0 },
  headlineMedium: { fontFamily: 'System', fontSize: 28, fontWeight: '400' as const, letterSpacing: 0 },
  headlineSmall: { fontFamily: 'System', fontSize: 24, fontWeight: '400' as const, letterSpacing: 0 },
  titleLarge: { fontFamily: 'System', fontSize: 22, fontWeight: '500' as const, letterSpacing: 0 },
  titleMedium: { fontFamily: 'System', fontSize: 16, fontWeight: '500' as const, letterSpacing: 0.15 },
  titleSmall: { fontFamily: 'System', fontSize: 14, fontWeight: '500' as const, letterSpacing: 0.1 },
  bodyLarge: { fontFamily: 'System', fontSize: 16, fontWeight: '400' as const, letterSpacing: 0.15 },
  bodyMedium: { fontFamily: 'System', fontSize: 14, fontWeight: '400' as const, letterSpacing: 0.25 },
  bodySmall: { fontFamily: 'System', fontSize: 12, fontWeight: '400' as const, letterSpacing: 0.4 },
  labelLarge: { fontFamily: 'System', fontSize: 14, fontWeight: '500' as const, letterSpacing: 0.1 },
  labelMedium: { fontFamily: 'System', fontSize: 12, fontWeight: '500' as const, letterSpacing: 0.5 },
  labelSmall: { fontFamily: 'System', fontSize: 11, fontWeight: '500' as const, letterSpacing: 0.5 },
};

export const lightTheme = {
  ...MD3LightTheme,
  fonts: configureFonts({ config: fontConfig }),
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.primary,
    primaryContainer: '#dbeafe',
    onPrimary: colors.white,
    onPrimaryContainer: colors.primaryDark,
    secondary: colors.gray[600],
    secondaryContainer: colors.gray[100],
    background: colors.white,
    surface: colors.white,
    surfaceVariant: colors.gray[50],
    onBackground: colors.gray[900],
    onSurface: colors.gray[900],
    onSurfaceVariant: colors.gray[600],
    outline: colors.gray[300],
    outlineVariant: colors.gray[200],
    error: colors.danger,
    onError: colors.white,
    errorContainer: '#fef2f2',
    elevation: {
      level0: 'transparent',
      level1: colors.gray[50],
      level2: colors.gray[100],
      level3: colors.gray[100],
      level4: colors.gray[200],
      level5: colors.gray[200],
    },
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  fonts: configureFonts({ config: fontConfig }),
  colors: {
    ...MD3DarkTheme.colors,
    primary: colors.primaryLight,
    primaryContainer: '#1e3a8a',
    onPrimary: colors.white,
    onPrimaryContainer: '#bfdbfe',
    secondary: colors.gray[400],
    secondaryContainer: colors.gray[800],
    background: colors.gray[900],
    surface: colors.gray[900],
    surfaceVariant: colors.gray[800],
    onBackground: colors.gray[100],
    onSurface: colors.gray[100],
    onSurfaceVariant: colors.gray[400],
    outline: colors.gray[600],
    outlineVariant: colors.gray[700],
    error: colors.dangerLight,
    onError: colors.white,
    errorContainer: '#450a0a',
    elevation: {
      level0: 'transparent',
      level1: colors.gray[800],
      level2: colors.gray[700],
      level3: colors.gray[700],
      level4: colors.gray[600],
      level5: colors.gray[600],
    },
  },
};
